### ISSUE TITLE
Installs the most recent release instead of the latest release

### ISSUE THREAD

**Issue by achingbrain** [alanshaw/iim#8]
There's currently a `latest` tag (`ipfs@0.37.0`) and a `next` tag (`ipfs@0.38.0-rc.6`) on npm.

The default behaviour of `iis use js` seems to be to pick whatever was published last - it should probably use the `latest` tag instead otherwise people will get release candidates when they are probably after stable releases.

**Comment by andrew** [comment]
@alanshaw looks like this was fixed in #15, I think this can be closed now?

**Comment by alanshaw** [comment]
IIRC it picks the highest semver version and doesn't use the 'latest' tag. The PR excludes prereleases so it fixes the problem for 99% of the time since most people release newer versions they don't necessarily want people to rely on yet as prereleases not stable versions.
